### ISSUE TITLE
32:9 (5120 x 1440) Support 

### ISSUE THREAD

**Issue by AddonsXI** [Joshhhuaaa/EnhancedSCCTVersus#1]
I have a monitor that is 32:9 (5120 x 1440), when I try to run the game at this resolution it will crash. Is it expected that this resolution will crash the game? I notice you do have 7680 x 4320 support, however this is still 16:9 ratio. Is it possible for you to support these newer ultrawide resolutions? Here is an example of someone playing Chaos Theory on 32:9 (https://www.youtube.com/watch?v=wnm69ZH_PR4). This resolution allows for a breathtaking field of view, however usually comes with the issue of the HUD being stuck in the very corners of the screen instead of the middle. I believe the Youtube video I linked might also being using some extra mod to re-center the HUD which is very helpful on ultrawide displays. Anyways, please consider support for ultrawide ratios like 32:9, it is a very fun way to play PC games! If you would let me to troubleshoot or test anything I'm available.

**Comment by Joshhhuaaa** [comment]
The video you posted is Chaos Theory’s single player with ThirteenAG’s Widescreen Fix. The single player runs on an entirely different engine than the SCCT Versus, so these should be treated as 2 separate games.

Unfortunately, SCCT Versus only stretches the image for aspect ratios wider than 4:3 aspect ratio. While some prefer stretched to black bars, there's no increase in the field of view for wider aspect ratios like 16:9. Therefore, playing on 32:9 won't offer any real benefit. It's probably better to stick to resolutions like 1920x1440 (4:3) or 2560x1440 (16:9). While 16:9 does stretch, it is not as severe as 32:9 which would look terrible.

---

As you can see below, whether it's 1920x1440, 2560x1440, or 5120x1440, the image is simply stretched.

1920x1440 (4:3)
![SCCTVersus_4by3](https://github.com/Joshhhuaaa/EnhancedSCCTVersus/assets/41166025/f036b135-782e-4c88-8126-540ee328b012)

---

2560x1440 (16:9)
![SCCTVersus_16by9](https://github.com/Joshhhuaaa/EnhancedSCCTVersus/assets/41166025/48112c56-8680-44d3-b141-61c11a754c8f)

---
5120x1440 (32:9)
![SCCTVersus_32by9](https://github.com/Joshhhuaaa/EnhancedSCCTVersus/assets/41166025/1eca7a3d-211b-482a-bd43-6e811c6f9dc2)

---

If you're still interested on playing in 32:9, even with the stretched display, and want to troubleshoot to prevent crashes, try adjusting your`Default.ini` in the System folder. Set the resolution manually:
```
FullscreenViewportX=5120
FullscreenViewportY=1440
```
Then, navigate to your profile saves directory and open `<Username>_prf.ini`. Set `ScreenRes` to `-1` and save. When set to `-1`, it will directly read the resolution specified in `Default.ini`, bypassing the presets. Usually, I don't recommend using `-1` because it comes with a graphics quality bug. However, for testing purposes, you can see if it crashes or not.

It would be nice to support 16:9 and possibly ultrawide aspect ratios like 21:9 and 32:9 without stretching the game or HUD while also increasing the horizontal field of view. However, I can’t natively do it in the game’s code, we are very limited with what we can modify. Someone who's experienced at making patches like ThirteenAG's Widescreen Fixes but for SCCT Versus might be able to do this, but I don't have the experience to make such a patch.

**Comment by Joshhhuaaa** [comment]
There might be a chance it just crashes, I never tried such a wide resolution. 32:9 obviously wouldn't look good without support but surprised it crashes the game entirely. I wonder if 7680x4320 would also crash the game, that was only put there for futureproof and when you select it, it should round down to your monitor's native 16:9 resolution. The screenshot I posted above that is 5120x1440 was just a demonstration on how it would look like, I just stretched my 1440p screenshot for that example.

You could see if the game crashes with dgVoodoo2 removed (delete or move D3D8.dll out of System folder). If the game works fine without dgVoodoo2, it might be the GeForce 4 GPU emulation not handling such an extreme resolution, you could see if increasing the VRAM in dgVoodoo.conf helps to prevent a crash, possibly running out of memory.

```
VideoCard                           = geforce_ti_4800
VRAM                                = 256
```
